### ISSUE TITLE
-fuse-ld=lld

### ISSUE THREAD

**Issue by NikitaZhinov** [cppshizoidS/PathFinding#2]
The compiler is shocked by this move "-fuse-ld=lld":
clang:
[build] : && clang++ -g -fuse-ld=lld CMakeFiles/PahtFinding.dir/src/Application.cpp.o CMakeFiles/PahtFinding.dir/src/Button.cpp.o CMakeFiles/PahtFinding.dir/src/Pathfinder.cpp.o CMakeFiles/PahtFinding.dir/src/Vertex_Array.cpp.o CMakeFiles/PahtFinding.dir/src/main.cpp.o -o PahtFinding  -lsfml-graphics  -lsfml-window  -lsfml-system && :
[build] clang++: error: invalid linker name in argument '-fuse-ld=lld'

gcc:
[build] : && g++ -g -fuse-ld=lld CMakeFiles/PahtFinding.dir/src/Application.cpp.o CMakeFiles/PahtFinding.dir/src/Button.cpp.o CMakeFiles/PahtFinding.dir/src/Pathfinder.cpp.o CMakeFiles/PahtFinding.dir/src/Vertex_Array.cpp.o CMakeFiles/PahtFinding.dir/src/main.cpp.o -o PahtFinding  -lsfml-graphics  -lsfml-window  -lsfml-system && :
[build] collect2: fatal error: cannot find «ld»

**Comment by cppshizoidS** [comment]
install lld linker in your system for build
https://src.fedoraproject.org/rpms/lld
https://packages.debian.org/bookworm/lld
https://archlinux.org/packages/extra/x86_64/lld/
it is faster linker than gnu sucks ld
